name: Inject Config & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Inject OneSignal Key
        run: |
          echo "window.MX_OS_REST_KEY = \"${{ secrets.ONESIGNAL_REST_KEY }}\";" > mx-config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
